contentsBundle\Entity\confSezioni:
    type: entity
    table: conf_sezioni
    id:
        idSezione:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_sezione
            generator:
                strategy: IDENTITY
    fields:
        livello:
            type: integer
            nullable: true
            options:
                unsigned: false
        titolo:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false        
        linkPreview:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: link_preview
        fieldPreview:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: field_preview
        keyField:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: key_field
        tabella:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        bundle:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        box:
            type: boolean
            nullable: false
            options:
                unsigned: false
        edit:
            type: boolean
            nullable: false
            options:
                unsigned: false
        remove:
            type: boolean
            nullable: false
            options:
                unsigned: false
        insert:
            type: boolean
            nullable: false
            options:
                unsigned: false
                
        stato_abilitato:
            type: boolean
            nullable: false
            options:
                unsigned: false
        stato:
            type: boolean
            nullable: false
            default: 1
            options:
                unsigned: false
        per_page:
            type: integer
            nullable: false
            default: 10
            options:
                unsigned: true
        ordine:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: 0
    manyToOne:
        idGruppo:
          targetEntity: confSezioniGruppi
          joinColumn:
            name: id_gruppo
            referencedColumnName: id
    lifecycleCallbacks: {  }
