contentsBundle\Entity\confTable:
    type: entity
    table: null
    repositoryClass: contentsBundle\Repository\confTableRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        field:
            type: string
            length: '255'
        name:
            type: string
            length: 255
        comment:
            type: text
            nullable: true
        stato:
            type: boolean
            nullable: false
        view_scheda:
            default: 1
            type: boolean
            nullable: false
        view_frontend:
            default: 1
            type: boolean
            nullable: false
        view_detail:
            default: 1
            type: boolean
            nullable: true   
        length_detail:            
            type: integer
            length: 7
            nullable: true            
        ordine:
            type: integer
            nullable: false
            options:
                unsigned: true
    manyToOne:
        idSezione:
          targetEntity: confSezioni
          joinColumn:
            name: id_sezione
            referencedColumnName: id_sezione
    lifecycleCallbacks: {  }
