<?php

namespace contentsBundle\Repository;

/**
 * boxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class boxRepository extends \Doctrine\ORM\EntityRepository
{
}
