<?php

namespace contentsBundle\Repository;

/**
 * conf_sezioni_box_configRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class conf_sezioni_box_configRepository extends \Doctrine\ORM\EntityRepository
{
}
