<?php

namespace contentsBundle\Repository;

/**
 * conf_sezioni_boxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class conf_sezioni_boxRepository extends \Doctrine\ORM\EntityRepository
{
}
