<?php

namespace contentsBundle\Repository;

/**
 * confSezioniRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class confSezioniRepository extends \Doctrine\ORM\EntityRepository
{
}
