<?php

namespace contentsBundle\Repository;

/**
 * confSezioniGruppiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class confSezioniGruppiRepository extends \Doctrine\ORM\EntityRepository
{
}
