<?php

namespace contentsBundle\Repository;

/**
 * confTableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class confTableRepository extends \Doctrine\ORM\EntityRepository
{
}
