<?php

namespace contentsBundle\Repository;

/**
 * contentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class contentsRepository extends \Doctrine\ORM\EntityRepository
{
    public function fieldExists($fieldname){
        
        return $this->_class->hasField($fieldname);
    }
}
